# @cutlass_dsl — generated by cutlass_dsl_repository.

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "cutlass",
    srcs = glob(["nvidia_cutlass_dsl/**/*.py"]),
    data = glob(
        ["nvidia_cutlass_dsl/**"],
        exclude = ["nvidia_cutlass_dsl/**/*.py"],
    ),
    imports = [
        # `import nvidia_cutlass_dsl` — the DSL locates its MLIR binaries
        # and cu* runtime relative to this package.
        ".",
        # `import cutlass` — this line replaces the shim wheel's
        # executable .pth (sys.path.insert of dsl_packages).
        "nvidia_cutlass_dsl/dsl_packages",
    ],
)
