"""Module extension: resolve the pip plane directly from pyproject.toml.

RFC docs/rfc_pyproject_direct_resolution.md. There is NO lock file in the
source tree: this extension runs a hash-pinned uv binary over
pyproject.toml at evaluation time and materializes the resolved,
hash-pinned requirements into the @pypi_resolution repository, which
rules_python's pip.parse consumes as its requirements_lock label (so the
whole wheel/venv machinery — including the site-packages layout torch's
CUDA preload needs — stays on the standard rules_python path).

Pinning story: the resolved content becomes an attribute of the
@pypi_resolution repo, and module-extension results are recorded in
MODULE.bazel.lock — that committed file is where the pip plane's pins
live now. Resolution re-runs only when its watched inputs (pyproject,
declared args, this file, the uv pin) change.

Resolution policy (extras, indexes, strategy) is declared at the use site
in MODULE.bazel — this file is mechanism only.
"""

load(":uv.bzl", "UV_BINARIES", "UV_VERSION")

def _platform(mctx):
    os_name = mctx.os.name.lower()
    arch = mctx.os.arch
    if "linux" in os_name and arch in ("amd64", "x86_64"):
        return "x86_64-unknown-linux-gnu"
    fail("pypi_resolve: unsupported platform {}/{} (pin more uv binaries in uv.bzl)".format(os_name, arch))

_REPO_BUILD = """\
load("@rules_python//python:defs.bzl", "py_library")

exports_files(["requirements.txt"])

# The resolved set as an importable module, so guard tests read it with a
# plain `import resolved_manifest` — no runfiles-path games.
py_library(
    name = "manifest",
    srcs = ["resolved_manifest.py"],
    imports = ["."],
    visibility = ["//visibility:public"],
)
"""

def _pypi_resolution_repo_impl(repository_ctx):
    content = repository_ctx.attr.content
    if "'''" in content:
        fail("pypi_resolve: resolved requirements unexpectedly contain triple quotes")
    repository_ctx.file("requirements.txt", content)
    repository_ctx.file(
        "resolved_manifest.py",
        '"""Generated by the pypi_resolve extension. Do not edit."""\n\n' +
        "RESOLVED_REQUIREMENTS = r'''\n" + content + "'''\n",
    )
    repository_ctx.file("BUILD.bazel", _REPO_BUILD)

_pypi_resolution_repo = repository_rule(
    implementation = _pypi_resolution_repo_impl,
    attrs = {
        # The full resolved requirements text. Living in an attribute is
        # what gets it recorded (and therefore pinned) in MODULE.bazel.lock.
        "content": attr.string(mandatory = True),
    },
)

def _impl(mctx):
    root_tags = None
    for mod in mctx.modules:
        if mod.is_root:
            root_tags = mod.tags.resolve
    if not root_tags or len(root_tags) != 1:
        fail("pypi_resolve: exactly one resolve() tag must be declared by the root module")
    tag = root_tags[0]

    platform = _platform(mctx)
    url, sha256 = UV_BINARIES[platform]
    mctx.download_and_extract(
        url = url,
        output = "uv_dist",
        sha256 = sha256,
        stripPrefix = "uv-" + platform,
    )

    pyproject = mctx.path(tag.pyproject)
    mctx.watch(pyproject)
    out_file = mctx.path("requirements.txt")

    result = mctx.execute(
        [
            str(mctx.path("uv_dist/uv")),
            "pip",
            "compile",
            str(pyproject),
            # The header would embed absolute output-base paths and churn
            # MODULE.bazel.lock across machines; suppress it.
            "--no-header",
            "-o",
            str(out_file),
        ] + tag.args,
        environment = {
            # Never read or write host state.
            "HOME": str(mctx.path("uv_home")),
            "UV_CACHE_DIR": str(mctx.path("uv_cache")),
            "UV_NO_CONFIG": "1",
        },
        timeout = 600,
    )
    if result.return_code != 0:
        fail("pypi_resolve: uv {} failed:\n{}".format(UV_VERSION, result.stderr))

    _pypi_resolution_repo(
        name = "pypi_resolution",
        content = mctx.read(out_file),
    )

pypi_resolve = module_extension(
    implementation = _impl,
    tag_classes = {
        "resolve": tag_class(
            attrs = {
                "pyproject": attr.label(
                    mandatory = True,
                    doc = "The single human-edited source of dependency intent.",
                ),
                "args": attr.string_list(
                    mandatory = True,
                    doc = "Full uv pip compile policy flags, declared visibly at the use site.",
                ),
            },
        ),
    },
    doc = "Resolves the pip plane from pyproject.toml; pins live in MODULE.bazel.lock.",
)
