#!/usr/bin/env python3

import json
import sys
import urllib.request
from pathlib import Path

COMPONENTS = {
    "libs_core": ("nvidia-cutlass-dsl-libs-core", "py3-none-any"),
    "libs_base": ("nvidia-cutlass-dsl-libs-base", "cp312-cp312-manylinux_2_28_x86_64"),
    "libs_cu12": ("nvidia-cutlass-dsl-libs-cu12", "cp312-cp312-manylinux_2_28_x86_64"),
    "libs_cu13": ("nvidia-cutlass-dsl-libs-cu13", "cp312-cp312-manylinux_2_28_x86_64"),
}
PLATFORM = "x86_64-unknown-linux-gnu"
OUT = Path(__file__).resolve().parent.parent / "bazel" / "cutlass_dsl" / "wheels.bzl"

HEADER = '''"""Hash-pinned nvidia-cutlass-dsl libs wheels.

GENERATED by tools/update_cutlass_dsl_wheels.py — do not edit by hand.
Regenerate when bumping the DSL version; the (url, sha256) pairs come from
PyPI's release metadata.

Lockstep invariant (RFC rfc_hermetic_cutedsl_layer.md, O3): all components
of one entry MUST share one version — this dict is the single place that
enforces what the dropped shim wheel used to enforce via `==` pins.

Python ABI coupling: libs_base/libs_cu* are cp312 wheels, matched to the
hermetic toolchain in MODULE.bazel. Bumping the Python version requires
regenerating this dict with the matching ABI tag.
"""

CUTLASS_DSL_WHEELS = {
'''


def wheel_entry(package: str, version: str, tag: str) -> tuple[str, str]:
    with urllib.request.urlopen(f"https://pypi.org/pypi/{package}/{version}/json") as resp:
        release = json.load(resp)
    for file_info in release["urls"]:
        if file_info["filename"].endswith(f"-{tag}.whl"):
            return file_info["url"], file_info["digests"]["sha256"]
    raise SystemExit(f"{package}=={version}: no wheel with tag {tag}")


def main() -> None:
    versions = sys.argv[1:]
    if not versions:
        raise SystemExit(__doc__)
    chunks = [HEADER]
    for version in versions:
        chunks.append(f'    "{version}": {{\n        "{PLATFORM}": {{\n')
        for component, (package, tag) in COMPONENTS.items():
            url, sha256 = wheel_entry(package, version, tag)
            chunks.append(
                f'            "{component}": (\n'
                f'                "{url}",\n'
                f'                "{sha256}",\n'
                f"            ),\n"
            )
        chunks.append("        },\n    },\n")
    chunks.append("}\n")
    OUT.write_text("".join(chunks))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
